filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/www/html/storage/logs/*.log
    fields:
      app: monitoria
      env: production
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info